version: "3.7"

services:
  mutagen:
    build:
      context: .
      dockerfile: mutagen.Dockerfile
    init: true
    container_name: "mutagen"
    volumes:
    - hackathon_digitalumni:/var/www/html

  php:
    volumes:
    - hackathon_digitalumni:/var/www/html

  crond:
    volumes:
    - hackathon_digitalumni:/var/www/html

  nginx:
    volumes:
    - hackathon_digitalumni:/var/www/html

volumes:
  hackathon_digitalumni:
